title: Insurance Bot Docs
description: Customer SOP and flow documentation
markdown: kramdown
kramdown:
  input: GFM
baseurl: "/insurance-bot"
url: "https://moksa-technologies.github.io"
exclude:
  - Customer_SOP.docx
